/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author User1
 */
public class SetupFrame extends javax.swing.JFrame {

    /**
     * Creates new form SetupFrame
     */
    public SetupFrame() {
        super.setTitle("Configure Initial Conditions");
        initComponents();
        pack();
        rngGenBtnActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rngTxt = new javax.swing.JTextField();
        rngGenBtn = new javax.swing.JButton();
        qTxt = new javax.swing.JTextField();
        pTxt = new javax.swing.JTextField();
        empCtnTxt = new javax.swing.JTextField();
        floorCountTxt = new javax.swing.JTextField();
        tickCountTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        genSimBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Starting Employee Count:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("<html>Emp\\Dev floor change chance per tick (<i>p</i>):");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("<html>Client arrival chance per tick (<i>q</i>):");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Randomisation Seed:");

        rngGenBtn.setText("Generate");
        rngGenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rngGenBtnActionPerformed(evt);
            }
        });

        qTxt.setText("0.001");

        pTxt.setText("0.005");

        empCtnTxt.setText("10");

        floorCountTxt.setText("7");
        floorCountTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floorCountTxtActionPerformed(evt);
            }
        });

        tickCountTxt.setText("2880");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Total Tick Count:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Number of floors (Including ground floor):");

        jTextField1.setText("10");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Starting Developer Count:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addComponent(tickCountTxt)
                    .addComponent(floorCountTxt)
                    .addComponent(qTxt)
                    .addComponent(pTxt)
                    .addComponent(empCtnTxt)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rngTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rngGenBtn)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tickCountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(floorCountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empCtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rngTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(rngGenBtn))
                .addContainerGap())
        );

        genSimBtn.setText("Generate Simulation");
        genSimBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genSimBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(genSimBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(genSimBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void errorMsg(String message) {
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * Checks that a given set of text boxes contain at least some text
     *
     * @param textBoxes The set of textBoxes to test
     * @return true if all fields are present, false otherwise
     */
    public static boolean presenceCheck(javax.swing.JTextField... textBoxes) {
        boolean valid = textBoxes.length > 0;
        for (javax.swing.JTextField textBox : textBoxes) {
            valid &= !"".equals(textBox.getText());
        }
        return valid;
    }

    private void rngGenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rngGenBtnActionPerformed
        Random rnd = new Random();
        rngTxt.setText( String.valueOf( rnd.nextLong() ) );
    }//GEN-LAST:event_rngGenBtnActionPerformed

    private void genSimBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genSimBtnActionPerformed
        if (!presenceCheck(empCtnTxt, jTextField1, rngTxt, pTxt, qTxt, tickCountTxt, floorCountTxt)) {
            errorMsg("Please ensure all fields are present.");
            return;
        }
        try {
            double p = Double.parseDouble(pTxt.getText());
            double q = Double.parseDouble(qTxt.getText());
            if (p > 1 || p < 0 || q > 1 || q < 0 ) {
                throw new Exception();
            }
        } catch (Exception e) {
            errorMsg("Please ensure P & Q are real values between 0 and 1 inclusive.");
            return;
        }

        try {
            int n = Integer.parseInt(empCtnTxt.getText());
            if (n < 0) {
                throw new Exception();
            }
            n = Integer.parseInt(jTextField1.getText());
            if (n < 0) {
                throw new Exception();
            }
        } catch (Exception e) {
            errorMsg("Please ensure the number of people is numeric, greater than 0, and less than the largest integer.");
            return;
        }

        try {
            long n = Long.parseLong(rngTxt.getText());
        } catch (Exception e) {
            errorMsg("Please ensure the randomisation seed is numeric and less than the largest long.");
            return;
        }
        
        try {
            long n = Integer.parseInt(floorCountTxt.getText());
            if ( n < 3 ) throw new Exception();
        } catch (Exception e) {
            errorMsg("Please ensure the floor count is numeric, greater than 3, and less than the largest integer.");
            return;
        }
        try {
            long n = Long.parseLong(tickCountTxt.getText());
            if ( n < 1 ) throw new Exception();
        } catch (Exception e) {
            errorMsg("Please ensure the tick count is numeric, greater than 0, and less than the largest long.");
            return;
        }
        this.dispose();
    }//GEN-LAST:event_genSimBtnActionPerformed

    private void floorCountTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floorCountTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floorCountTxtActionPerformed
    public int getTickCount() { 
        return Integer.parseInt(tickCountTxt.getText());
    }
    
    public int getFloorCount() { 
        return Integer.parseInt(floorCountTxt.getText());
    }
    
    public int getStartingDevCount() { 
        return Integer.parseInt(jTextField1.getText());
    }
    
    public int getStartingEmployeeCount() {
        return Integer.parseInt(empCtnTxt.getText());
    }

    public double getP() {
        return Double.parseDouble(pTxt.getText());
    }

    public double getQ() {
        return Double.parseDouble(qTxt.getText());
    }

    public long getSeed() {
        return Long.parseLong(rngTxt.getText());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField empCtnTxt;
    private javax.swing.JTextField floorCountTxt;
    private javax.swing.JButton genSimBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField pTxt;
    private javax.swing.JTextField qTxt;
    private javax.swing.JButton rngGenBtn;
    private javax.swing.JTextField rngTxt;
    private javax.swing.JTextField tickCountTxt;
    // End of variables declaration//GEN-END:variables
}
